# Generated by Django 3.2 on 2022-02-03 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='Название категории')),
                ('slug', models.SlugField(max_length=70, unique=True, verbose_name='Часть URL категории')),
                ('image', models.ImageField(upload_to='./Category/', verbose_name='Фото категории')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ('title',),
            },
        ),
        migrations.CreateModel(
            name='Swiper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=70, verbose_name='Название слайда')),
                ('text', models.CharField(max_length=450, verbose_name='Текст слайда')),
                ('image', models.ImageField(upload_to='./Swiper/', verbose_name='Фото сорта')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания слайда')),
                ('available', models.BooleanField(default=True, verbose_name='Активный слайд')),
            ],
            options={
                'verbose_name': 'Слайд',
                'verbose_name_plural': 'Слайды',
                'ordering': ('title',),
            },
        ),
        migrations.CreateModel(
            name='Seedling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=70, verbose_name='Название сорта')),
                ('slug', models.SlugField(max_length=85, unique=True, verbose_name='Часть URL сорта')),
                ('image', models.ImageField(upload_to='./Seedlings/', verbose_name='Фото сорта')),
                ('short_description', models.CharField(blank=True, max_length=100, verbose_name='Краткое описание сорта')),
                ('full_description', models.TextField(blank=True, verbose_name='Полное описание сорта')),
                ('retail_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Розничная цена')),
                ('wholesale_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Оптовая цена')),
                ('stock', models.PositiveIntegerField(verbose_name='Кол-во саженцев')),
                ('available', models.BooleanField(default=True, verbose_name='Доступность')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Дата редактирования')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seedlings', to='seedlings.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Саженец',
                'verbose_name_plural': 'Саженцы',
                'ordering': ('title',),
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст комментария')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания комментария')),
                ('author_name', models.CharField(max_length=50, verbose_name='Имя автора')),
                ('seedling', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='seedlings.seedling', verbose_name='Сорт')),
            ],
            options={
                'verbose_name': 'Комментарий',
                'verbose_name_plural': 'Комментарии',
                'ordering': ('created',),
            },
        ),
        migrations.AddConstraint(
            model_name='category',
            constraint=models.UniqueConstraint(fields=('title',), name='unique category value'),
        ),
        migrations.AddConstraint(
            model_name='seedling',
            constraint=models.UniqueConstraint(fields=('title', 'category'), name='unique seedling value'),
        ),
        migrations.AlterIndexTogether(
            name='seedling',
            index_together={('id', 'slug')},
        ),
        migrations.AddConstraint(
            model_name='comment',
            constraint=models.UniqueConstraint(fields=('seedling', 'text'), name='unique comment value'),
        ),
        migrations.AlterIndexTogether(
            name='comment',
            index_together={('seedling',)},
        ),
    ]
