# Generated by Django 3.2 on 2022-02-01 12:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='Название категории')),
                ('slug', models.SlugField(max_length=70, unique=True, verbose_name='Часть URL категории')),
                ('image', models.ImageField(upload_to='./', verbose_name='Фото категории')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ('title',),
            },
        ),
        migrations.CreateModel(
            name='Seedling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=70, verbose_name='Название сорта')),
                ('slug', models.SlugField(max_length=85, unique=True, verbose_name='Часть URL сорта')),
                ('image', models.ImageField(upload_to='./', verbose_name='Фото сорта')),
                ('short_description', models.CharField(blank=True, max_length=150, verbose_name='Краткое описание сорта')),
                ('full_description', models.TextField(blank=True, verbose_name='Полное описание сорта')),
                ('retail_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Розничная цена')),
                ('wholesale_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Оптовая цена')),
                ('stock', models.PositiveIntegerField(verbose_name='Кол-во саженцев')),
                ('available', models.BooleanField(default=True, verbose_name='Доступность')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Дата редактирования')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seedlings', to='seedlings.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Саженец',
                'verbose_name_plural': 'Саженцы',
                'ordering': ('title',),
                'index_together': {('id', 'slug')},
            },
        ),
    ]
