version: '3.3'

volumes:
  postgres_data:
  static_value:
  media_value:
  data_set:

services:

  db:
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ../.env
  
  nginx:
    image: nginx:1.19.3
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - static_value:/var/www/django/static:ro
      - media_value:/var/www/django/media:ro
      - /etc/ssl/:/etc/ssl/
    depends_on:
      - web
  
  web:
    build:
      context: ../backend
      dockerfile: Dockerfile
    restart: always
    volumes:
      - static_value:/app/static:rw
      - media_value:/app/media:rw
      - data_set:/app/data:rw
    depends_on:
      - db
    env_file:
      - ../.env
