# Generated by Django 3.2 on 2022-03-26 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seedlings', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('display_order', 'title'), 'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='seedling',
            options={'ordering': ('display_order', 'title'), 'verbose_name': 'Саженец', 'verbose_name_plural': 'Саженцы'},
        ),
    ]
