# Generated by Django 3.2 on 2022-02-07 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seedlings', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='swiper',
            options={'ordering': ('display_order',), 'verbose_name': 'Слайд', 'verbose_name_plural': 'Слайды'},
        ),
        migrations.AddField(
            model_name='swiper',
            name='display_order',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Порядок отображения'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='swiper',
            name='text',
            field=models.CharField(max_length=260, verbose_name='Текст слайда'),
        ),
    ]
