# Generated by Django 3.2 on 2022-02-27 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seedlings', '0002_auto_20220207_1925'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='comment',
            name='unique comment value',
        ),
        migrations.AddConstraint(
            model_name='comment',
            constraint=models.UniqueConstraint(fields=('seedling', 'author_name', 'text'), name='unique comment value'),
        ),
    ]
