# Generated by Django 3.2 on 2022-03-01 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seedlings', '0003_auto_20220227_1237'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ('-created',), 'verbose_name': 'Комментарий', 'verbose_name_plural': 'Комментарии'},
        ),
    ]
