# Generated by Django 3.2 on 2022-03-03 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('markup', models.TextField(verbose_name='Разметка страницы')),
            ],
            options={
                'verbose_name': 'Разметка страницы',
                'verbose_name_plural': 'Разметка страницы',
            },
        ),
    ]
