# Generated by Django 3.2 on 2022-03-03 12:12

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='markup',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Разметка страницы'),
        ),
    ]
